// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://komapxcxdrqtvbceeqly.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvbWFweGN4ZHJxdHZiY2VlcWx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMyOTA5NDIsImV4cCI6MjA0ODg2Njk0Mn0.uUQ2Mk3CxRmSqGqpkq90hS4Ng0Lxe-aFcLetFw3KagU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);